sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="dmtn-084"
    # AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "yvNjLNuqgYvgtHhulM2cj8OJJzaAdvCMxOHd3oguPsQ4XyN9RW4qacilhHYlX53Sr3TJByZpR3UwY+kMxDPDCjI5GGV7EZms+FQTpB5/KBxLWSqh8744Z2fhXZB3RSo6YXcwn8RAoXyOMpsoP+lcByMMgQScBcPOxQplte2TqbvkwJWR5XEYXMp7mMyqwDQ9W2AZu12XXfbKTBwgOncRHXjSS+PphLC4+UDb5hhTFDMUMH6+evsDNsCm/GLuhsV85jrDrlXVt/xpfe2YtOQUg29kRmQ22abxWLneEUiFFIW/MEFt05HKmDrA6YK50vJVdTIedNIVgbe+RFP7TLznos3TyZhZq6O8hK8MbPEZg22BYLDxjMNc/dQ0K3o7Tm4QFw869/MI5W6DZ/26xyVKEnf/a8zKuMiSfMHTup8c5RrDsCnmLRpFFip6WmenGGEo/z/k3i3C6Rf9AoHER/EwLELYfCOQXELioQK2q6S4tZ2cN0IdBo7ncpun4c3+nvAKA4lqGUPd4ehaIUtZcnc2iGilss02NXBcuY1iAQd+Z4mGJkj/c6SF8q3spVR5A21a6t7HJmYLPaz9R5JBzL59NgDLEBKzcVnnq4Ju+Q9wsKMpiXz9wl277VAg14t+OrNppgjb6i+0Yulq++JNgcfm9WguNDlISSwACLgB6+AZR9g="
    - secure: "Z+V4PXrt4PvWFwd1m3OK4TJHTmexaIgNaffNUxjgaFDYcPOuf0zBAEJqNmO1ZZhOjewQy4UBO9XpOOeIrBSUMnxxEW8ttAorCkNEosq1Wah1Fl/RbPE9JxSFy7H+Om7plI/Uk56DQt7FKHQEWYnrGRiuOn30FlZuHJULiiuu4OVCfexUxSWxqlB7uEVds+JDcEbtYW62O/4+36Bo92up9evjs1BImn0G+9cg9x4SsNCGJBkO1k9v6zxT0Pe2hCVdrY+lzLQnmzcXIEG1eTNOwS9PrcWVKZk2cMNPVTQVI7DGxGQDsS3NN03v6mme9aLm+ulq1jZ3V8GpcrCPy+uXMzR/V0zBUeue6yNPd59C7x3JVRF52MRoNBZUUo0+MBKAZwZD9cj/rGX+tV2Kg2LfzTWbZiAaE1QjBbBc/tn2nf1Nt2Wmp4fVff0bDetsVam+iZuUgY6U3uPw3+rnHiCvRZt/yJhZKVRtyzekKRdmRWC4WeX5HxPtP8zEYqtHDnFayz1ODAMI0AW2r3txen5H+HymvWcNN6Y+5wBOlayz/Cwoh60z0o61HOaXTTgASo3CSlk1WKApbR9pXSmh2oKOoxNe5dr31Vn6mWL3h6xMYTOuHJmse9EMK8ZQdoB11XIDWyDTujHz94rq5MjcsY5hXnQxsuecdJhhiREf4WoKgxg="
